// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type List struct {
	ID          int64            `json:"id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Task struct {
	ID           int64            `json:"id"`
	Title        string           `json:"title"`
	Description  pgtype.Text      `json:"description"`
	IsDone       bool             `json:"is_done"`
	DueDate      pgtype.Timestamp `json:"due_date"`
	Priority     int32            `json:"priority"`
	ParentListID pgtype.Int8      `json:"parent_list_id"`
	ParentTaskID pgtype.Int8      `json:"parent_task_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
